# Generated by Django 5.2.9 on 2025-12-31 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_programacion_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_indisponibles', to='users.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indisponibilidad (Excepción)',
                'verbose_name_plural': 'Indisponibilidades',
                'unique_together': {('usuario', 'turno')},
            },
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
